apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: local-test
spec:
  selector:
    app: debug
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
